### Question

Create a data pipeline for this dataset 
https://www.kaggle.com/datasets/sriharshaeedala/airline-delay/data

which should include following
- Extract (load csv)
- Transform (clean data and transform data if needed)
- Load (save the cleaned data in csv file)

Also create visualization of 
- correlation of attributes
- distribution of values in attributes 
- and any 3 other graph using seaborn 

Note: Also generate insight from it and explain it. 

Submission should be done in github repo with ipynb file or google collab link.

---

### Dataset Description

The dataset is structured as a tabular format with rows representing unique combinations of year, month, carrier, and airport. Each row contains information on various metrics, including flight counts, delay counts, cancellation and diversion counts, and delay breakdowns by different factors. The columns provide specific details such as carrier codes and names, airport codes and names, and counts of delays attributed to carrier, weather, NAS, security, and late aircraft arrivals. The structured format ensures that users can easily query, analyze, and visualize the data to derive meaningful insights.

- year: The year of the data.
- month: The month of the data.
- carrier: Carrier code.
- carrier_name: Carrier name.
- airport: Airport code.
- airport_name: Airport name.
- arr_flights: Number of arriving flights.
- arr_del15: Number of flights delayed by 15 minutes or more.
- carrier_ct: Carrier count (delay due to the carrier).
- weather_ct: Weather count (delay due to weather).
- nas_ct: NAS (National Airspace System) count (delay due to the NAS).
- security_ct: Security count (delay due to security).
- late_aircraft_ct: Late aircraft count (delay due to late aircraft arrival).
- arr_cancelled: Number of flights canceled.
- arr_diverted: Number of flights diverted.
- arr_delay: Total arrival delay.
- carrier_delay: Delay attributed to the carrier.
- weather_delay: Delay attributed to weather.
- nas_delay: Delay attributed to the NAS.
- security_delay: Delay attributed to security.
- late_aircraft_delay: Delay attributed to late aircraft arrival.

## STEP 1: EXTRACT

### 1.1 loading the data from kaggle

In [88]:
# importing the necessary libraries for ETL process
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

In [89]:
# boilerplate code from kaggle to load the dataset
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Airline_Delay_Cause.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "sriharshaeedala/airline-delay",
  file_path
)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [90]:
# verifying if data is properly loaded or not
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

In [91]:
df.tail()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
171661,2013,8,YV,Mesa Airlines Inc.,TRI,"Bristol/Johnson City/Kingsport, TN: Tri Cities",7.0,1.0,0.78,0.0,...,0.0,0.0,0.0,0.0,23.0,18.0,0.0,5.0,0.0,0.0
171662,2013,8,YV,Mesa Airlines Inc.,YUM,"Yuma, AZ: Yuma MCAS/Yuma International",2.0,1.0,0.00,0.0,...,0.0,1.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0,17.0
171663,2013,8,YV,Mesa Airlines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",2.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
171664,2013,8,DL,Delta Air Lines Inc.,SBN,"South Bend, IN: South Bend International",1.0,1.0,1.00,0.0,...,0.0,0.0,0.0,0.0,18.0,18.0,0.0,0.0,0.0,0.0
171665,2013,8,F9,Frontier Airlines Inc.,MTJ,"Montrose/Delta, CO: Montrose Regional",1.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 1.2 performing data validation

In [92]:
# total rows
total_data = len(df)  
total_data

171666

In [93]:
# getting the statistics of numerical columns
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
year,171666.0,2018.551361,2.890006,2013.0,2016.00,2019.00,2021.00,2023.00
month,171666.0,6.493633,3.440908,1.0,4.00,7.00,9.00,12.00
arr_flights,171426.0,362.528467,992.894662,1.0,50.00,100.00,250.00,21977.00
arr_del15,171223.0,66.434387,179.540694,0.0,6.00,17.00,47.00,4176.00
carrier_ct,171426.0,20.796615,50.315176,0.0,2.16,6.40,17.26,1293.91
weather_ct,171426.0,2.250347,7.314252,0.0,0.00,0.40,1.86,266.42
nas_ct,171426.0,19.381147,61.675244,0.0,1.00,3.91,11.71,1884.42
security_ct,171426.0,0.157096,0.717405,0.0,0.00,0.00,0.00,58.69
late_aircraft_ct,171426.0,23.770554,72.393477,0.0,1.23,5.00,15.26,2069.07
arr_cancelled,171426.0,7.530497,43.654880,0.0,0.00,1.00,4.00,4951.00
arr_diverted,171426.0,0.863387,3.772853,0.0,0.00,0.00,1.00,197.00
arr_delay,171426.0,4239.487330,12618.566050,0.0,335.00,1018.00,2884.00,438783.00
carrier_delay,171426.0,1437.185124,4215.677812,0.0,110.00,375.00,1109.00,196944.00
weather_delay,171426.0,222.563497,821.086511,0.0,0.00,18.00,146.00,31960.00
nas_delay,171426.0,920.651704,3423.509335,0.0,34.00,146.00,477.00,112018.00
security_delay,171426.0,7.382725,41.779985,0.0,0.00,0.00,0.00,3760.00
late_aircraft_delay,171426.0,1651.700063,5221.878385,0.0,65.00,320.00,1070.00,227959.00

In [94]:
print(df.dtypes)

year                     int64
month                    int64
carrier                 object
carrier_name            object
airport                 object
airport_name            object
arr_flights            float64
arr_del15              float64
carrier_ct             float64
weather_ct             float64
nas_ct                 float64
security_ct            float64
late_aircraft_ct       float64
arr_cancelled          float64
arr_diverted           float64
arr_delay              float64
carrier_delay          float64
weather_delay          float64
nas_delay              float64
security_delay         float64
late_aircraft_delay    float64
dtype: object

In [95]:
# checking if delay minutes and number of delays are same or not and
for i in range(20):
    index = np.random.randint(0, total_data)
    count, cc,wc,nc,sc,lac = df.loc[index, ['arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct', 'security_ct', 'late_aircraft_ct']]
    mins, cm,wm,nm,sm,lm = df.loc[index, ['arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']]
    if mins != round(cm+wm+nm+sm+lm):
        print(f'{index}: Minutes NOT matched')
        print(f'T:{mins} : {cm}, {wm}, {nm}, {sm}, {lm} : {cm+wm+nm+sm+lm}')
    if count != round(cc+wc+nc+sc+lac):
         print(f'{index}: Count NOT matched')
         print(f'T:{count} : {cc}, {wc}, {nc}, {sc}, {lac}: {cc+wc+nc+sc+lac}')

In [96]:
# total percentage of data that is null
null_values = df.isna().sum()
print('columns \t\t\t nullvalues%')
for i in range(len(null_values)):
    print(f'{null_values.index[i]} \t\t\t {round(null_values[i]/total_data*100, 3)}%')

columns 			 nullvalues%
year 			 0.0%
month 			 0.0%
carrier 			 0.0%
carrier_name 			 0.0%
airport 			 0.0%
airport_name 			 0.0%
arr_flights 			 0.14%
arr_del15 			 0.258%
carrier_ct 			 0.14%
weather_ct 			 0.14%
nas_ct 			 0.14%
security_ct 			 0.14%
late_aircraft_ct 			 0.14%
arr_cancelled 			 0.14%
arr_diverted 			 0.14%
arr_delay 			 0.14%
carrier_delay 			 0.14%
weather_delay 			 0.14%
nas_delay 			 0.14%
security_delay 			 0.14%
late_aircraft_delay 			 0.14%

/var/folders/lq/wz2w0wfj3gn14q_q15mhm9sc0000gn/T/ipykernel_58462/2139138028.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f'{null_values.index[i]} \t\t\t {round(null_values[i]/total_data*100, 3)}%')

In [97]:
# looking at random set of data
df.iloc[135:175,:]

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
135,2023,8,AA,American Airlines Inc.,FLL,"Fort Lauderdale, FL: Fort Lauderdale-Hollywood...",447.0,129.0,40.22,3.59,...,0.25,57.76,5.0,3.0,11667.0,3675.0,514.0,1169.0,9.0,6300.0
136,2023,8,AA,American Airlines Inc.,FSD,"Sioux Falls, SD: Joe Foss Field",62.0,25.0,9.74,0.00,...,0.00,10.11,0.0,0.0,2900.0,800.0,0.0,344.0,0.0,1756.0
137,2023,8,AA,American Airlines Inc.,GEG,"Spokane, WA: Spokane International",93.0,25.0,10.35,0.00,...,0.00,10.84,1.0,0.0,3519.0,714.0,0.0,143.0,0.0,2662.0
138,2023,8,AA,American Airlines Inc.,GRR,"Grand Rapids, MI: Gerald R. Ford International",166.0,56.0,17.95,1.69,...,0.00,31.22,2.0,2.0,8476.0,2361.0,76.0,263.0,0.0,5776.0
139,2023,8,AA,American Airlines Inc.,GSO,"Greensboro/High Point, NC: Piedmont Triad Inte...",122.0,33.0,11.03,1.49,...,0.05,16.20,1.0,0.0,3809.0,496.0,169.0,154.0,3.0,2987.0
140,2023,8,AA,American Airlines Inc.,GSP,"Greer, SC: Greenville-Spartanburg International",123.0,44.0,10.40,4.01,...,0.11,26.85,0.0,0.0,3849.0,753.0,324.0,122.0,27.0,2623.0
141,2023,8,AA,American Airlines Inc.,HNL,"Honolulu, HI: Daniel K Inouye International",186.0,41.0,14.52,0.00,...,0.00,11.55,0.0,2.0,2878.0,959.0,0.0,370.0,0.0,1549.0
142,2023,8,AA,American Airlines Inc.,HSV,"Huntsville, AL: Huntsville International-Carl ...",9.0,5.0,1.28,0.00,...,0.00,3.70,0.0,0.0,581.0,125.0,0.0,3.0,0.0,453.0
143,2023,8,AA,American Airlines Inc.,IAD,"Washington, DC: Washington Dulles International",76.0,12.0,4.85,0.75,...,0.00,5.73,0.0,0.0,834.0,338.0,49.0,23.0,0.0,424.0
144,2023,8,AA,American Airlines Inc.,IAH,"Houston, TX: George Bush Intercontinental/Houston",683.0,180.0,75.08,8.10,...,0.00,77.69,8.0,1.0,17333.0,7728.0,838.0,1105.0,0.0,7662.0
145,2023,8,AA,American Airlines Inc.,ICT,"Wichita, KS: Wichita Dwight D Eisenhower National",73.0,25.0,14.01,0.00,...,0.00,9.38,3.0,0.0,4343.0,2493.0,0.0,51.0,0.0,1799.0
146,2023,8,AA,American Airlines Inc.,ILM,"Wilmington, NC: Wilmington International",184.0,59.0,20.56,3.80,...,0.00,25.94,3.0,0.0,4670.0,1496.0,309.0,430.0,0.0,2435.0
147,2023,8,AA,American Airlines Inc.,IND,"Indianapolis, IN: Indianapolis International",561.0,170.0,50.09,4.02,...,1.15,90.06,5.0,0.0,17791.0,4270.0,345.0,1042.0,51.0,12083.0
148,2023,8,AA,American Airlines Inc.,JAC,"Jackson, WY: Jackson Hole",99.0,15.0,3.25,1.39,...,0.00,7.63,0.0,0.0,1365.0,207.0,192.0,187.0,0.0,779.0
149,2023,8,AA,American Airlines Inc.,JAX,"Jacksonville, FL: Jacksonville International",604.0,182.0,56.04,4.56,...,1.40,94.37,23.0,1.0,15927.0,3880.0,405.0,1273.0,44.0,10325.0
150,2023,8,AA,American Airlines Inc.,JFK,"New York, NY: John F. Kennedy International",1220.0,307.0,108.58,16.89,...,1.73,90.82,8.0,2.0,27925.0,10897.0,2402.0,4092.0,41.0,10493.0
151,2023,8,AA,American Airlines Inc.,KOA,"Kona, HI: Ellison Onizuka Kona International a...",62.0,15.0,5.69,0.00,...,0.00,4.62,0.0,1.0,1007.0,561.0,0.0,124.0,0.0,322.0
152,2023,8,AA,American Airlines Inc.,LAS,"Las Vegas, NV: Harry Reid International",1219.0,413.0,126.67,12.53,...,3.50,180.83,11.0,1.0,36270.0,10163.0,1045.0,4053.0,193.0,20816.0
153,2023,8,AA,American Airlines Inc.,LAX,"Los Angeles, CA: Los Angeles International",2611.0,661.0,228.63,24.32,...,0.66,275.60,19.0,8.0,64858.0,26362.0,2603.0,5576.0,53.0,30264.0
154,2023,8,AA,American Airlines Inc.,LBB,"Lubbock, TX: Lubbock Preston Smith International",75.0,21.0,7.12,0.00,...,0.00,13.35,2.0,0.0,3293.0,944.0,0.0,62.0,0.0,2287.0
155,2023,8,AA,American Airlines Inc.,LEX,"Lexington, KY: Blue Grass",72.0,30.0,11.45,0.00,...,0.00,17.51,1.0,0.0,4172.0,1392.0,0.0,74.0,0.0,2706.0
156,2023,8,AA,American Airlines Inc.,LGA,"New York, NY: LaGuardia",1558.0,372.0,131.89,29.50,...,2.01,138.40,26.0,8.0,34763.0,11381.0,2683.0,3942.0,111.0,16646.0
157,2023,8,AA,American Airlines Inc.,LIH,"Lihue, HI: Lihue Airport",62.0,9.0,4.20,0.00,...,0.00,3.39,0.0,0.0,969.0,292.0,0.0,45.0,0.0,632.0
158,2023,8,AA,American Airlines Inc.,LIT,"Little Rock, AR: Bill and Hillary Clinton Nat ...",57.0,16.0,3.96,0.00,...,0.00,9.59,2.0,0.0,1777.0,494.0,0.0,66.0,0.0,1217.0
159,2023,8,AA,American Airlines Inc.,MCI,"Kansas City, MO: Kansas City International",513.0,167.0,57.12,6.14,...,0.20,89.18,7.0,0.0,13922.0,4404.0,506.0,686.0,38.0,8288.0
160,2023,8,AA,American Airlines Inc.,MCO,"Orlando, FL: Orlando International",1556.0,417.0,116.27,19.65,...,0.00,180.87,24.0,12.0,44135.0,11845.0,2606.0,6022.0,0.0,23662.0
161,2023,8,AA,American Airlines Inc.,MDT,"Harrisburg, PA: Harrisburg International",75.0,22.0,10.31,0.00,...,0.00,9.75,0.0,0.0,2528.0,594.0,0.0,70.0,0.0,1864.0
162,2023,8,AA,American Airlines Inc.,MEM,"Memphis, TN: Memphis International",428.0,135.0,39.04,5.98,...,0.00,70.02,9.0,0.0,12945.0,4058.0,514.0,686.0,0.0,7687.0
163,2023,8,AA,American Airlines Inc.,MFE,"Mission/McAllen/Edinburg, TX: McAllen Internat...",141.0,25.0,12.53,0.02,...,0.00,11.05,2.0,0.0,1386.0,482.0,1.0,47.0,0.0,856.0
164,2023,8,AA,American Airlines Inc.,MHT,"Manchester, NH: Manchester Boston Regional",17.0,4.0,3.04,0.00,...,0.00,0.66,0.0,0.0,313.0,229.0,0.0,44.0,0.0,40.0
165,2023,8,AA,American Airlines Inc.,MIA,"Miami, FL: Miami International",4604.0,1094.0,315.59,30.91,...,6.24,389.93,86.0,34.0,102683.0,31859.0,3022.0,20060.0,366.0,47376.0
166,2023,8,AA,American Airlines Inc.,MKE,"Milwaukee, WI: General Mitchell International",214.0,74.0,25.66,3.04,...,0.00,39.38,3.0,0.0,7645.0,2779.0,300.0,265.0,0.0,4301.0
167,2023,8,AA,American Airlines Inc.,MRY,"Monterey, CA: Monterey Regional",73.0,26.0,10.04,0.00,...,0.00,13.44,2.0,0.0,2955.0,810.0,0.0,114.0,0.0,2031.0
168,2023,8,AA,American Airlines Inc.,MSN,"Madison, WI: Dane County Regional-Truax Field",207.0,57.0,18.43,2.16,...,0.00,30.50,1.0,0.0,5855.0,2007.0,195.0,187.0,0.0,3466.0
169,2023,8,AA,American Airlines Inc.,MSO,"Missoula, MT: Missoula Montana",44.0,11.0,2.94,0.00,...,0.00,3.70,0.0,0.0,554.0,93.0,0.0,142.0,0.0,319.0
170,2023,8,AA,American Airlines Inc.,MSP,"Minneapolis, MN: Minneapolis-St Paul Internati...",402.0,86.0,35.23,3.34,...,0.00,33.31,2.0,0.0,7966.0,3772.0,269.0,864.0,0.0,3061.0
171,2023,8,AA,American Airlines Inc.,MSY,"New Orleans, LA: Louis Armstrong New Orleans I...",538.0,152.0,48.12,5.77,...,0.00,81.26,9.0,2.0,13254.0,4943.0,508.0,707.0,0.0,7096.0
172,2023,8,AA,American Airlines Inc.,MTJ,"Montrose/Delta, CO: Montrose Regional",62.0,18.0,6.50,0.47,...,0.00,11.02,0.0,0.0,2010.0,581.0,9.0,0.0,0.0,1420.0
173,2023,8,AA,American Airlines Inc.,MYR,"Myrtle Beach, SC: Myrtle Beach International",134.0,28.0,7.92,3.02,...,0.00,12.56,5.0,0.0,1547.0,339.0,254.0,105.0,0.0,849.0
174,2023,8,AA,American Airlines Inc.,OGG,"Kahului, HI: Kahului Airport",124.0,23.0,8.66,0.00,...,0.00,6.51,5.0,0.0,1185.0,558.0,0.0,301.0,0.0,326.0

In [98]:
# checking if unique or not
pk_columns = ['year', 'month', 'carrier', 'airport']
duplicate_count = df.duplicated(subset=pk_columns).sum()
duplicate_count

np.int64(0)

In [101]:
delay_ct_cols = ['carrier_ct', 'weather_ct', 'nas_ct', 'security_ct', 'late_aircraft_ct']
delay_mins_cols = ['carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

zero_delay_ct_rows = df[(df[delay_ct_cols] == 0).all(axis=1)]
zero_delay_mins_rows = df[(df[delay_mins_cols] == 0).all(axis=1)]
zero_total_delay_ct = df[(df['arr_delay'] == 0)]
zero_total_delay_mins = df[(df['arr_del15'] == 0)]

print(f"Rows where all delay causes count is 0: {len(zero_delay_ct_rows)} ")
print(f"Total 0 count: {len(zero_total_delay_ct)}")
print("---")
print(f"Rows where all delay mins is 0: {len(zero_delay_mins_rows)} ")
print(f"Total 0 mins: {len(zero_total_delay_mins)}")

Rows where all delay causes count is 0: 6788
Total 0 count: 6788
---
Rows where all delay mins is 0: 6788
Total 0 mins: 6585

In [ ]:
# so basically causes count is fine, however the total time is kindof illogical around 200 data points

In [103]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
all_zero_numeric = df[
    (df[numeric_cols] == 0).all(axis=1)
]

print("Rows where all numeric values are zero:", len(all_zero_numeric))

Rows where all numeric values are zero: 0

In [104]:
invalid_delay_rows = df[df['arr_del15'] > df['arr_flights']]
print("Invalid delay rows:", len(invalid_delay_rows))

Invalid delay rows: 0

### From initial exploration, following things are deduced:

1. Total rows: 171,666
2. All columns are in the respective datatypes i.e. numerical columns in int and float, string columns in object
3. For non-null values, the total delay count and total delay minutes is exactly the sum of different causes of counts of delay and minutes of delay
4. Around 0.14% of most columns is null, however max is of arr_del15 with 0.258%
5. Primary key for this dataset: (year, month, carrier, airport)
6. NO duplicate values
7. 6788 instances had no delay. However, 6585 instances are sure to have no delays but the random 200-ish datapoints seem illogical
8. almost all data integrity checks show that the data is good.

---

## STEP 2: TRANSFORM